import { useState, useEffect } from 'react';
import { WeeklyReport } from '../types/analytics';
import { useAuth } from '../context/AuthContext';
import { 
  FileText, Sparkles, Brain, Clock, Target, 
  TrendingUp, TrendingDown, ClipboardList, Copy, 
  Check, Loader2, AlertCircle, Eye, Mail
} from 'lucide-react';

export default function WeeklyReportsView() {
  const { session } = useAuth();
  const [reports, setReports] = useState<WeeklyReport[]>([]);
  const [selectedReport, setSelectedReport] = useState<WeeklyReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  
  // Tab within report: 'details' vs 'email'
  const [activeSubTab, setActiveSubTab] = useState<'details' | 'email'>('details');
  const [emailHtml, setEmailHtml] = useState<string>('');
  const [loadingEmail, setLoadingEmail] = useState(false);

  const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:3001';

  // Fetch reports list
  const fetchReports = async () => {
    if (!session?.access_token) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`${apiUrl}/api/analytics/weekly-reports`, {
        headers: { 'Authorization': `Bearer ${session.access_token}` }
      });
      const data = await res.json();
      if (data.success) {
        setReports(data.reports);
        if (data.reports.length > 0) {
          setSelectedReport(data.reports[0]);
        }
      } else {
        throw new Error(data.error || 'Failed to fetch reports');
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Error loading reports');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, [session]);

  // Fetch email HTML when selected report changes or sub-tab switches to email
  useEffect(() => {
    if (!selectedReport || activeSubTab !== 'email' || !session?.access_token) return;

    setLoadingEmail(true);
    fetch(`${apiUrl}/api/analytics/weekly-reports/${selectedReport.id}/email`, {
      headers: { 'Authorization': `Bearer ${session.access_token}` }
    })
    .then(res => {
      if (res.headers.get('content-type')?.includes('text/html')) {
        return res.text();
      }
      return res.json().then(d => { throw new Error(d.error || 'Failed to fetch email HTML'); });
    })
    .then(html => {
      setEmailHtml(html);
    })
    .catch(err => {
      console.error(err);
    })
    .finally(() => {
      setLoadingEmail(false);
    });
  }, [selectedReport, activeSubTab, session]);

  // Generate a report on demand
  const handleGenerateReport = async () => {
    if (!session?.access_token || generating) return;
    setGenerating(true);
    setError(null);
    try {
      const res = await fetch(`${apiUrl}/api/analytics/weekly-reports/generate`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${session.access_token}`,
          'Content-Type': 'application/json'
        }
      });
      const data = await res.json();
      if (data.success) {
        const newReport = data.report;
        setReports(prev => [newReport, ...prev]);
        setSelectedReport(newReport);
        setActiveSubTab('details');
      } else {
        throw new Error(data.error || 'Failed to generate report');
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Error generating report');
    } finally {
      setGenerating(false);
    }
  };

  const handleCopyEmailHtml = () => {
    if (!emailHtml) return;
    navigator.clipboard.writeText(emailHtml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="py-20 flex flex-col items-center justify-center gap-3">
        <Loader2 className="w-8 h-8 text-blue-500 animate-spin" />
        <p className="text-sm text-slate-500">Loading focus analytics and reports...</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      
      {/* View Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
            Weekly AI Reports
            <Sparkles className="w-4 h-4 text-violet-400" />
          </h2>
          <p className="text-xs text-slate-400">
            Generate and review comprehensive focus evaluations generated by AI
          </p>
        </div>
        <button
          onClick={handleGenerateReport}
          disabled={generating}
          className="px-4 py-2.5 bg-violet-600 hover:bg-violet-700 disabled:bg-slate-800 text-white rounded-xl text-xs font-bold transition-all shadow-lg shadow-violet-600/10 flex items-center gap-2 active:scale-95 disabled:scale-100 disabled:opacity-50"
        >
          {generating ? (
            <>
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
              Compiling Focus Metrics...
            </>
          ) : (
            <>
              <Brain className="w-3.5 h-3.5" />
              Generate Weekly Report
            </>
          )}
        </button>
      </div>

      {error && (
        <div className="p-4 bg-red-950/20 border border-red-500/20 rounded-2xl flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
          <p className="text-xs text-slate-400 leading-relaxed">{error}</p>
        </div>
      )}

      {reports.length === 0 ? (
        <div className="p-12 border border-dashed border-white/[0.08] rounded-3xl text-center space-y-4 bg-white/[0.01]">
          <div className="w-12 h-12 bg-white/[0.03] rounded-2xl border border-white/[0.05] flex items-center justify-center mx-auto text-slate-500">
            <FileText className="w-6 h-6" />
          </div>
          <div className="space-y-1">
            <h3 className="text-sm font-semibold text-white">No reports generated yet</h3>
            <p className="text-xs text-slate-500 max-w-xs mx-auto">
              Get an in-depth breakdown of your focus times, scores, distractions, and unlock habits.
            </p>
          </div>
          <button
            onClick={handleGenerateReport}
            disabled={generating}
            className="px-4 py-2 bg-white text-black hover:bg-slate-200 text-xs font-semibold rounded-xl transition-all"
          >
            Generate First Report
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 items-start">
          
          {/* Historical Reports List (Left Sidebar) */}
          <div className="lg:col-span-1 space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 px-1">
              Report History
            </h3>
            <div className="space-y-1.5 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
              {reports.map((report) => {
                const isSelected = selectedReport?.id === report.id;
                return (
                  <button
                    key={report.id}
                    onClick={() => {
                      setSelectedReport(report);
                      setActiveSubTab('details');
                    }}
                    className={`w-full p-3.5 text-left rounded-xl transition-all border flex flex-col gap-1.5 group ${
                      isSelected 
                        ? 'bg-violet-600/10 border-violet-500/30 text-white' 
                        : 'bg-white/[0.02] border-white/[0.04] text-slate-400 hover:border-white/10 hover:text-slate-200'
                    }`}
                  >
                    <span className="text-xs font-bold leading-none">
                      {report.start_date} to {report.end_date}
                    </span>
                    <span className="text-[10px] opacity-75 font-semibold">
                      Focus Time: {report.focus_hours}h • Score: {report.focus_score}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Active Report View (Right Detail Panel) */}
          <div className="lg:col-span-3 bg-gradient-to-br from-white/[0.03] to-white/[0.01] border border-white/[0.08] rounded-3xl p-6 shadow-xl space-y-6">
            
            {/* Header / Tabs */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-white/[0.06] pb-4 gap-4">
              <div>
                <h3 className="text-sm font-bold text-white">
                  Report: {selectedReport?.start_date} to {selectedReport?.end_date}
                </h3>
                <p className="text-[11px] text-slate-500 font-semibold mt-0.5">
                  Generated on {selectedReport && new Date(selectedReport.created_at).toLocaleDateString()}
                </p>
              </div>

              {/* Toggle tabs inside report */}
              <div className="flex bg-[#121217] rounded-xl p-1 border border-white/[0.05] text-[11px] font-semibold text-slate-400 shrink-0 self-start sm:self-auto">
                <button
                  onClick={() => setActiveSubTab('details')}
                  className={`px-3 py-1.5 rounded-lg transition-all flex items-center gap-1.5 ${
                    activeSubTab === 'details' 
                      ? 'bg-violet-600 text-white shadow-sm' 
                      : 'hover:text-slate-200'
                  }`}
                >
                  <Eye className="w-3.5 h-3.5" />
                  View Details
                </button>
                <button
                  onClick={() => setActiveSubTab('email')}
                  className={`px-3 py-1.5 rounded-lg transition-all flex items-center gap-1.5 ${
                    activeSubTab === 'email' 
                      ? 'bg-violet-600 text-white shadow-sm' 
                      : 'hover:text-slate-200'
                  }`}
                >
                  <Mail className="w-3.5 h-3.5" />
                  Email Copy
                </button>
              </div>
            </div>

            {/* Sub-tab Rendering */}
            {activeSubTab === 'details' && selectedReport && (
              <div className="space-y-6">
                
                {/* AI Summary Callout with premium style */}
                <div className="relative overflow-hidden rounded-2xl border border-violet-500/20 bg-gradient-to-br from-violet-950/10 via-slate-900 to-indigo-950/10 p-5 shadow-lg">
                  <div className="absolute top-0 right-0 w-24 h-24 bg-violet-600/5 blur-2xl rounded-full pointer-events-none"></div>
                  <div className="relative z-10 space-y-2">
                    <span className="flex items-center gap-1 text-[10px] uppercase tracking-wider text-violet-400 font-bold">
                      <Brain className="w-3.5 h-3.5" />
                      AI Focus Summary
                    </span>
                    <p className="text-sm text-slate-200 leading-relaxed italic pl-3 border-l-2 border-violet-500">
                      "{selectedReport.ai_summary}"
                    </p>
                  </div>
                </div>

                {/* Metrics Cards Grid */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  {/* Focus Hours */}
                  <div className="p-4 bg-white/[0.02] border border-white/[0.06] rounded-2xl text-center space-y-1">
                    <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold block">Focus Time</span>
                    <span className="text-xl font-black text-white block">{selectedReport.focus_hours}h</span>
                    <span className="text-[9px] text-slate-400 font-medium block">logged this week</span>
                  </div>

                  {/* Focus Score */}
                  <div className="p-4 bg-white/[0.02] border border-white/[0.06] rounded-2xl text-center space-y-1">
                    <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold block">Focus Score</span>
                    <span className="text-xl font-black text-violet-400 block">{selectedReport.focus_score}/100</span>
                    <span className="text-[9px] text-slate-400 font-medium block">avg session quality</span>
                  </div>

                  {/* Productivity Change */}
                  <div className="p-4 bg-white/[0.02] border border-white/[0.06] rounded-2xl text-center space-y-1">
                    <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold block">Productivity Change</span>
                    <span className={`text-xl font-black flex items-center justify-center gap-0.5 ${
                      selectedReport.productivity_change >= 0 ? 'text-green-400' : 'text-red-400'
                    }`}>
                      {selectedReport.productivity_change >= 0 ? <TrendingUp className="w-4 h-4" /> : <TrendingDown className="w-4 h-4" />}
                      {selectedReport.productivity_change >= 0 ? '+' : ''}{selectedReport.productivity_change}%
                    </span>
                    <span className="text-[9px] text-slate-400 font-medium block">compared to last week</span>
                  </div>

                  {/* Completion Rate */}
                  {(() => {
                    const completionRate = selectedReport.session_count > 0 
                      ? Math.round((selectedReport.completed_count / selectedReport.session_count) * 100)
                      : 0;
                    return (
                      <div className="p-4 bg-white/[0.02] border border-white/[0.06] rounded-2xl text-center space-y-1">
                        <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold block">Completion Rate</span>
                        <span className="text-xl font-black text-green-400 block">{completionRate}%</span>
                        <span className="text-[9px] text-slate-400 font-medium block">
                          {selectedReport.completed_count}/{selectedReport.session_count} completed
                        </span>
                      </div>
                    );
                  })()}
                </div>

                {/* Grid details (Distractions vs Unlocks) */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-stretch">
                  
                  {/* Top Distractions */}
                  <div className="p-5 bg-white/[0.02] border border-white/[0.06] rounded-2xl flex flex-col">
                    <h4 className="text-xs font-bold text-white border-b border-white/[0.06] pb-2 mb-3 flex items-center gap-2">
                      <ClipboardList className="w-4 h-4 text-violet-400" />
                      Top Distractions Blocked
                    </h4>
                    {selectedReport.top_distractions.length === 0 ? (
                      <p className="text-[11px] text-slate-500 text-center my-auto">No distractions logged. Impressive!</p>
                    ) : (
                      <div className="space-y-2 flex-1">
                        {selectedReport.top_distractions.map((d, index) => (
                          <div key={index} className="flex items-center justify-between text-xs border-b border-white/[0.03] pb-1.5">
                            <span className="text-slate-300 font-medium truncate max-w-[150px]">{d.domain}</span>
                            <span className="text-slate-500 font-semibold">{d.count} attempts</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Emergency Unlocks reasons */}
                  <div className="p-5 bg-white/[0.02] border border-white/[0.06] rounded-2xl flex flex-col">
                    <h4 className="text-xs font-bold text-white border-b border-white/[0.06] pb-2 mb-3 flex items-center gap-2">
                      <AlertCircle className="w-4 h-4 text-violet-400" />
                      Emergency Unlock Override Reasons
                    </h4>
                    {Object.values(selectedReport.unlock_reasons).every(v => v === 0) ? (
                      <p className="text-[11px] text-slate-500 text-center my-auto">0 unlock overrides requested. Perfect discipline!</p>
                    ) : (
                      <div className="space-y-2 flex-1">
                        {Object.entries(selectedReport.unlock_reasons).map(([reason, count], index) => (
                          <div key={index} className="flex items-center justify-between text-xs border-b border-white/[0.03] pb-1.5">
                            <span className="text-slate-300 font-medium">{reason}</span>
                            <span className="text-slate-500 font-semibold">{count} overrides</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                </div>

              </div>
            )}

            {/* Email HTML Preview Tab */}
            {activeSubTab === 'email' && selectedReport && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <p className="text-[11px] text-slate-500 font-semibold">
                    Email-ready responsive newsletter preview:
                  </p>
                  <button
                    onClick={handleCopyEmailHtml}
                    disabled={!emailHtml || loadingEmail}
                    className="px-3 py-1.5 bg-[#121217] hover:bg-slate-800 border border-white/[0.05] rounded-xl text-[10px] font-bold text-slate-300 flex items-center gap-1.5 transition-all"
                  >
                    {copied ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-green-400" />
                        Copied Email HTML!
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5 text-violet-400" />
                        Copy Email HTML
                      </>
                    )}
                  </button>
                </div>

                {loadingEmail ? (
                  <div className="h-[400px] flex flex-col items-center justify-center gap-2 border border-white/[0.08] rounded-2xl bg-white/[0.01]">
                    <Loader2 className="w-5 h-5 text-violet-400 animate-spin" />
                    <p className="text-xs text-slate-500">Rendering email layout...</p>
                  </div>
                ) : (
                  <div className="border border-white/[0.08] rounded-2xl overflow-hidden bg-white">
                    <iframe
                      srcDoc={emailHtml}
                      title="Weekly Focus Report Email Version"
                      className="w-full h-[500px]"
                      sandbox="allow-same-origin"
                    />
                  </div>
                )}
              </div>
            )}

          </div>
        </div>
      )}
    </div>
  );
}
